### ISSUE TITLE
Invalid Hint block in Guides

### ISSUE THREAD

**Issue by co16353sidak** [thenativeweb/wolkenkit-documentation#47]
While I was going through this guide while working on a PR, I stumbled upon this line:-
`:::hint-congrats`
Not able to understand why this was added into this as it doesn't seem to be markdown syntax as such.
If it isn't of any purpose, shouldn't it be removed and if it should, seems like an easy fix for which I can go for.

link:- https://github.com/thenativeweb/wolkenkit-documentation/blob/master/lib/docs/latest/guides/creating-an-application-from-scratch/creating-the-client/index.md

<img width="362" alt="Screenshot 2019-03-16 at 12 39 56 AM" src="https://user-images.githubusercontent.com/35738138/54456377-06fcd980-4784-11e9-8897-96d69a6e2674.png">

**Comment by goloroden** [comment]
You are right that this is no valid markdown, but we are using an extension for our markdown parser internally, and these are some custom components we defined. See [here](https://github.com/thenativeweb/wolkenkit-documentation/blob/master/lib/components/Markdown.jsx#L48-L52) for where they are used.

For example, if you take a look at [this page](https://docs.wolkenkit.io/3.1.0/getting-started/contributing-to-wolkenkit/overview/), and scroll to its bottom, you can see a box with Sophie van Sky: All these boxes are defined with the appropriate `:::hint-xxx` definitions, and depending on what you use for `xxx`, you get a differently styled box.

I hope this helps :-)
